[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"

[[edge_functions]]
  path = "/netlify/edge-functions/chat"
  function = "chat"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = true

[dev]
framework = "next"
targetPort = 3000
port = 8888
